[package]
name = "yagber_dma"
version = "0.1.0"
edition = "2024"

[features]
trace = ["dep:tracing"]

[dependencies]
tracing = { workspace = true, optional = true }

yagber_app = { workspace = true }
yagber_cpu = { workspace = true }
yagber_memory = { workspace = true }
