[package]
name = "yagber_display"
version = "0.1.0"
edition = "2024"

[features]
default = []
trace = ["dep:tracing"]
frame_marker = []

[dependencies]
tracing = { workspace = true, optional = true }
winit = "0.30.11"
pixels = "0.15.0"

yagber_app = { workspace = true }
