[package]
name = "yagber_ppu"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }

yagber_app = { workspace = true }
yagber_clock = { workspace = true }
yagber_memory = { workspace = true }
