[package]
name = "yagber_cpu"
version = "0.1.0"
edition = "2024"

[dependencies]
arbitrary-int = { workspace = true }
tracing = { workspace = true }
yagber_clock = { workspace = true }
yagber_memory = { workspace = true }
