[package]
name = "yet-another-gb-rust-emulator_cpu"
version = "0.1.0"
edition = "2024"

[features]
default = ["break_on_unitialized_ram_read"]
break_on_unitialized_ram_read = []

[dependencies]
arbitrary-int = { workspace = true }
tracing = { workspace = true }
clock = { workspace = true }
