[package]
name = "yagber_link_cable"
version = "0.1.0"
edition = "2024"

[features]
default = []
trace = ["dep:tracing"]

[dependencies]
tracing = { workspace = true, optional = true }

yagber_app = { workspace = true }
yagber_memory = { workspace = true }
