[package]
name = "yagber_app"
version = "0.1.0"
edition = "2024"

[features]
default = []
trace = ["dep:tracing"]
trace-span = ["dep:tracing"]

[dependencies]
tracing = { workspace = true, optional = true }