pub fn convert_keyboard_input(
    keyboard_input: &winit::event::KeyEvent,
) -> yagber_input::keyboard::KeyboardInput {
    yagber_input::keyboard::KeyboardInput {
        state: convert_element_state(keyboard_input.state),
        key_code: convert_physical_key_code(keyboard_input.physical_key),
        logical_key: convert_logical_key(&keyboard_input.logical_key),
        text: keyboard_input.text.clone(),
    }
}

pub fn convert_element_state(element_state: winit::event::ElementState) -> yagber_input::KeyState {
    match element_state {
        winit::event::ElementState::Pressed => yagber_input::KeyState::Pressed,
        winit::event::ElementState::Released => yagber_input::KeyState::Released,
    }
}

pub fn convert_physical_native_key_code(
    native_key_code: winit::keyboard::NativeKeyCode,
) -> yagber_input::keyboard::NativeKeyCode {
    use yagber_input::keyboard::NativeKeyCode;
    match native_key_code {
        winit::keyboard::NativeKeyCode::Unidentified => NativeKeyCode::Unidentified,
        winit::keyboard::NativeKeyCode::Android(scan_code) => NativeKeyCode::Android(scan_code),
        winit::keyboard::NativeKeyCode::MacOS(scan_code) => NativeKeyCode::MacOS(scan_code),
        winit::keyboard::NativeKeyCode::Windows(scan_code) => NativeKeyCode::Windows(scan_code),
        winit::keyboard::NativeKeyCode::Xkb(key_code) => NativeKeyCode::Xkb(key_code),
    }
}
pub fn convert_physical_key_code(
    virtual_key_code: winit::keyboard::PhysicalKey,
) -> yagber_input::keyboard::KeyCode {
    use yagber_input::keyboard::KeyCode;
    match virtual_key_code {
        winit::keyboard::PhysicalKey::Unidentified(native_key_code) => {
            KeyCode::Unidentified(convert_physical_native_key_code(native_key_code))
        }
        winit::keyboard::PhysicalKey::Code(code) => match code {
            winit::keyboard::KeyCode::Backquote => KeyCode::Backquote,
            winit::keyboard::KeyCode::Backslash => KeyCode::Backslash,
            winit::keyboard::KeyCode::BracketLeft => KeyCode::BracketLeft,
            winit::keyboard::KeyCode::BracketRight => KeyCode::BracketRight,
            winit::keyboard::KeyCode::Comma => KeyCode::Comma,
            winit::keyboard::KeyCode::Digit0 => KeyCode::Digit0,
            winit::keyboard::KeyCode::Digit1 => KeyCode::Digit1,
            winit::keyboard::KeyCode::Digit2 => KeyCode::Digit2,
            winit::keyboard::KeyCode::Digit3 => KeyCode::Digit3,
            winit::keyboard::KeyCode::Digit4 => KeyCode::Digit4,
            winit::keyboard::KeyCode::Digit5 => KeyCode::Digit5,
            winit::keyboard::KeyCode::Digit6 => KeyCode::Digit6,
            winit::keyboard::KeyCode::Digit7 => KeyCode::Digit7,
            winit::keyboard::KeyCode::Digit8 => KeyCode::Digit8,
            winit::keyboard::KeyCode::Digit9 => KeyCode::Digit9,
            winit::keyboard::KeyCode::Equal => KeyCode::Equal,
            winit::keyboard::KeyCode::IntlBackslash => KeyCode::IntlBackslash,
            winit::keyboard::KeyCode::IntlRo => KeyCode::IntlRo,
            winit::keyboard::KeyCode::IntlYen => KeyCode::IntlYen,
            winit::keyboard::KeyCode::KeyA => KeyCode::KeyA,
            winit::keyboard::KeyCode::KeyB => KeyCode::KeyB,
            winit::keyboard::KeyCode::KeyC => KeyCode::KeyC,
            winit::keyboard::KeyCode::KeyD => KeyCode::KeyD,
            winit::keyboard::KeyCode::KeyE => KeyCode::KeyE,
            winit::keyboard::KeyCode::KeyF => KeyCode::KeyF,
            winit::keyboard::KeyCode::KeyG => KeyCode::KeyG,
            winit::keyboard::KeyCode::KeyH => KeyCode::KeyH,
            winit::keyboard::KeyCode::KeyI => KeyCode::KeyI,
            winit::keyboard::KeyCode::KeyJ => KeyCode::KeyJ,
            winit::keyboard::KeyCode::KeyK => KeyCode::KeyK,
            winit::keyboard::KeyCode::KeyL => KeyCode::KeyL,
            winit::keyboard::KeyCode::KeyM => KeyCode::KeyM,
            winit::keyboard::KeyCode::KeyN => KeyCode::KeyN,
            winit::keyboard::KeyCode::KeyO => KeyCode::KeyO,
            winit::keyboard::KeyCode::KeyP => KeyCode::KeyP,
            winit::keyboard::KeyCode::KeyQ => KeyCode::KeyQ,
            winit::keyboard::KeyCode::KeyR => KeyCode::KeyR,
            winit::keyboard::KeyCode::KeyS => KeyCode::KeyS,
            winit::keyboard::KeyCode::KeyT => KeyCode::KeyT,
            winit::keyboard::KeyCode::KeyU => KeyCode::KeyU,
            winit::keyboard::KeyCode::KeyV => KeyCode::KeyV,
            winit::keyboard::KeyCode::KeyW => KeyCode::KeyW,
            winit::keyboard::KeyCode::KeyX => KeyCode::KeyX,
            winit::keyboard::KeyCode::KeyY => KeyCode::KeyY,
            winit::keyboard::KeyCode::KeyZ => KeyCode::KeyZ,
            winit::keyboard::KeyCode::Minus => KeyCode::Minus,
            winit::keyboard::KeyCode::Period => KeyCode::Period,
            winit::keyboard::KeyCode::Quote => KeyCode::Quote,
            winit::keyboard::KeyCode::Semicolon => KeyCode::Semicolon,
            winit::keyboard::KeyCode::Slash => KeyCode::Slash,
            winit::keyboard::KeyCode::AltLeft => KeyCode::AltLeft,
            winit::keyboard::KeyCode::AltRight => KeyCode::AltRight,
            winit::keyboard::KeyCode::Backspace => KeyCode::Backspace,
            winit::keyboard::KeyCode::CapsLock => KeyCode::CapsLock,
            winit::keyboard::KeyCode::ContextMenu => KeyCode::ContextMenu,
            winit::keyboard::KeyCode::ControlLeft => KeyCode::ControlLeft,
            winit::keyboard::KeyCode::ControlRight => KeyCode::ControlRight,
            winit::keyboard::KeyCode::Enter => KeyCode::Enter,
            winit::keyboard::KeyCode::SuperLeft => KeyCode::SuperLeft,
            winit::keyboard::KeyCode::SuperRight => KeyCode::SuperRight,
            winit::keyboard::KeyCode::ShiftLeft => KeyCode::ShiftLeft,
            winit::keyboard::KeyCode::ShiftRight => KeyCode::ShiftRight,
            winit::keyboard::KeyCode::Space => KeyCode::Space,
            winit::keyboard::KeyCode::Tab => KeyCode::Tab,
            winit::keyboard::KeyCode::Convert => KeyCode::Convert,
            winit::keyboard::KeyCode::KanaMode => KeyCode::KanaMode,
            winit::keyboard::KeyCode::Lang1 => KeyCode::Lang1,
            winit::keyboard::KeyCode::Lang2 => KeyCode::Lang2,
            winit::keyboard::KeyCode::Lang3 => KeyCode::Lang3,
            winit::keyboard::KeyCode::Lang4 => KeyCode::Lang4,
            winit::keyboard::KeyCode::Lang5 => KeyCode::Lang5,
            winit::keyboard::KeyCode::NonConvert => KeyCode::NonConvert,
            winit::keyboard::KeyCode::Delete => KeyCode::Delete,
            winit::keyboard::KeyCode::End => KeyCode::End,
            winit::keyboard::KeyCode::Help => KeyCode::Help,
            winit::keyboard::KeyCode::Home => KeyCode::Home,
            winit::keyboard::KeyCode::Insert => KeyCode::Insert,
            winit::keyboard::KeyCode::PageDown => KeyCode::PageDown,
            winit::keyboard::KeyCode::PageUp => KeyCode::PageUp,
            winit::keyboard::KeyCode::ArrowDown => KeyCode::ArrowDown,
            winit::keyboard::KeyCode::ArrowLeft => KeyCode::ArrowLeft,
            winit::keyboard::KeyCode::ArrowRight => KeyCode::ArrowRight,
            winit::keyboard::KeyCode::ArrowUp => KeyCode::ArrowUp,
            winit::keyboard::KeyCode::NumLock => KeyCode::NumLock,
            winit::keyboard::KeyCode::Numpad0 => KeyCode::Numpad0,
            winit::keyboard::KeyCode::Numpad1 => KeyCode::Numpad1,
            winit::keyboard::KeyCode::Numpad2 => KeyCode::Numpad2,
            winit::keyboard::KeyCode::Numpad3 => KeyCode::Numpad3,
            winit::keyboard::KeyCode::Numpad4 => KeyCode::Numpad4,
            winit::keyboard::KeyCode::Numpad5 => KeyCode::Numpad5,
            winit::keyboard::KeyCode::Numpad6 => KeyCode::Numpad6,
            winit::keyboard::KeyCode::Numpad7 => KeyCode::Numpad7,
            winit::keyboard::KeyCode::Numpad8 => KeyCode::Numpad8,
            winit::keyboard::KeyCode::Numpad9 => KeyCode::Numpad9,
            winit::keyboard::KeyCode::NumpadAdd => KeyCode::NumpadAdd,
            winit::keyboard::KeyCode::NumpadBackspace => KeyCode::NumpadBackspace,
            winit::keyboard::KeyCode::NumpadClear => KeyCode::NumpadClear,
            winit::keyboard::KeyCode::NumpadClearEntry => KeyCode::NumpadClearEntry,
            winit::keyboard::KeyCode::NumpadComma => KeyCode::NumpadComma,
            winit::keyboard::KeyCode::NumpadDecimal => KeyCode::NumpadDecimal,
            winit::keyboard::KeyCode::NumpadDivide => KeyCode::NumpadDivide,
            winit::keyboard::KeyCode::NumpadEnter => KeyCode::NumpadEnter,
            winit::keyboard::KeyCode::NumpadEqual => KeyCode::NumpadEqual,
            winit::keyboard::KeyCode::NumpadHash => KeyCode::NumpadHash,
            winit::keyboard::KeyCode::NumpadMemoryAdd => KeyCode::NumpadMemoryAdd,
            winit::keyboard::KeyCode::NumpadMemoryClear => KeyCode::NumpadMemoryClear,
            winit::keyboard::KeyCode::NumpadMemoryRecall => KeyCode::NumpadMemoryRecall,
            winit::keyboard::KeyCode::NumpadMemoryStore => KeyCode::NumpadMemoryStore,
            winit::keyboard::KeyCode::NumpadMemorySubtract => KeyCode::NumpadMemorySubtract,
            winit::keyboard::KeyCode::NumpadMultiply => KeyCode::NumpadMultiply,
            winit::keyboard::KeyCode::NumpadParenLeft => KeyCode::NumpadParenLeft,
            winit::keyboard::KeyCode::NumpadParenRight => KeyCode::NumpadParenRight,
            winit::keyboard::KeyCode::NumpadStar => KeyCode::NumpadStar,
            winit::keyboard::KeyCode::NumpadSubtract => KeyCode::NumpadSubtract,
            winit::keyboard::KeyCode::Escape => KeyCode::Escape,
            winit::keyboard::KeyCode::Fn => KeyCode::Fn,
            winit::keyboard::KeyCode::FnLock => KeyCode::FnLock,
            winit::keyboard::KeyCode::PrintScreen => KeyCode::PrintScreen,
            winit::keyboard::KeyCode::ScrollLock => KeyCode::ScrollLock,
            winit::keyboard::KeyCode::Pause => KeyCode::Pause,
            winit::keyboard::KeyCode::BrowserBack => KeyCode::BrowserBack,
            winit::keyboard::KeyCode::BrowserFavorites => KeyCode::BrowserFavorites,
            winit::keyboard::KeyCode::BrowserForward => KeyCode::BrowserForward,
            winit::keyboard::KeyCode::BrowserHome => KeyCode::BrowserHome,
            winit::keyboard::KeyCode::BrowserRefresh => KeyCode::BrowserRefresh,
            winit::keyboard::KeyCode::BrowserSearch => KeyCode::BrowserSearch,
            winit::keyboard::KeyCode::BrowserStop => KeyCode::BrowserStop,
            winit::keyboard::KeyCode::Eject => KeyCode::Eject,
            winit::keyboard::KeyCode::LaunchApp1 => KeyCode::LaunchApp1,
            winit::keyboard::KeyCode::LaunchApp2 => KeyCode::LaunchApp2,
            winit::keyboard::KeyCode::LaunchMail => KeyCode::LaunchMail,
            winit::keyboard::KeyCode::MediaPlayPause => KeyCode::MediaPlayPause,
            winit::keyboard::KeyCode::MediaSelect => KeyCode::MediaSelect,
            winit::keyboard::KeyCode::MediaStop => KeyCode::MediaStop,
            winit::keyboard::KeyCode::MediaTrackNext => KeyCode::MediaTrackNext,
            winit::keyboard::KeyCode::MediaTrackPrevious => KeyCode::MediaTrackPrevious,
            winit::keyboard::KeyCode::Power => KeyCode::Power,
            winit::keyboard::KeyCode::Sleep => KeyCode::Sleep,
            winit::keyboard::KeyCode::AudioVolumeDown => KeyCode::AudioVolumeDown,
            winit::keyboard::KeyCode::AudioVolumeMute => KeyCode::AudioVolumeMute,
            winit::keyboard::KeyCode::AudioVolumeUp => KeyCode::AudioVolumeUp,
            winit::keyboard::KeyCode::WakeUp => KeyCode::WakeUp,
            winit::keyboard::KeyCode::Meta => KeyCode::Meta,
            winit::keyboard::KeyCode::Hyper => KeyCode::Hyper,
            winit::keyboard::KeyCode::Turbo => KeyCode::Turbo,
            winit::keyboard::KeyCode::Abort => KeyCode::Abort,
            winit::keyboard::KeyCode::Resume => KeyCode::Resume,
            winit::keyboard::KeyCode::Suspend => KeyCode::Suspend,
            winit::keyboard::KeyCode::Again => KeyCode::Again,
            winit::keyboard::KeyCode::Copy => KeyCode::Copy,
            winit::keyboard::KeyCode::Cut => KeyCode::Cut,
            winit::keyboard::KeyCode::Find => KeyCode::Find,
            winit::keyboard::KeyCode::Open => KeyCode::Open,
            winit::keyboard::KeyCode::Paste => KeyCode::Paste,
            winit::keyboard::KeyCode::Props => KeyCode::Props,
            winit::keyboard::KeyCode::Select => KeyCode::Select,
            winit::keyboard::KeyCode::Undo => KeyCode::Undo,
            winit::keyboard::KeyCode::Hiragana => KeyCode::Hiragana,
            winit::keyboard::KeyCode::Katakana => KeyCode::Katakana,
            winit::keyboard::KeyCode::F1 => KeyCode::F1,
            winit::keyboard::KeyCode::F2 => KeyCode::F2,
            winit::keyboard::KeyCode::F3 => KeyCode::F3,
            winit::keyboard::KeyCode::F4 => KeyCode::F4,
            winit::keyboard::KeyCode::F5 => KeyCode::F5,
            winit::keyboard::KeyCode::F6 => KeyCode::F6,
            winit::keyboard::KeyCode::F7 => KeyCode::F7,
            winit::keyboard::KeyCode::F8 => KeyCode::F8,
            winit::keyboard::KeyCode::F9 => KeyCode::F9,
            winit::keyboard::KeyCode::F10 => KeyCode::F10,
            winit::keyboard::KeyCode::F11 => KeyCode::F11,
            winit::keyboard::KeyCode::F12 => KeyCode::F12,
            winit::keyboard::KeyCode::F13 => KeyCode::F13,
            winit::keyboard::KeyCode::F14 => KeyCode::F14,
            winit::keyboard::KeyCode::F15 => KeyCode::F15,
            winit::keyboard::KeyCode::F16 => KeyCode::F16,
            winit::keyboard::KeyCode::F17 => KeyCode::F17,
            winit::keyboard::KeyCode::F18 => KeyCode::F18,
            winit::keyboard::KeyCode::F19 => KeyCode::F19,
            winit::keyboard::KeyCode::F20 => KeyCode::F20,
            winit::keyboard::KeyCode::F21 => KeyCode::F21,
            winit::keyboard::KeyCode::F22 => KeyCode::F22,
            winit::keyboard::KeyCode::F23 => KeyCode::F23,
            winit::keyboard::KeyCode::F24 => KeyCode::F24,
            winit::keyboard::KeyCode::F25 => KeyCode::F25,
            winit::keyboard::KeyCode::F26 => KeyCode::F26,
            winit::keyboard::KeyCode::F27 => KeyCode::F27,
            winit::keyboard::KeyCode::F28 => KeyCode::F28,
            winit::keyboard::KeyCode::F29 => KeyCode::F29,
            winit::keyboard::KeyCode::F30 => KeyCode::F30,
            winit::keyboard::KeyCode::F31 => KeyCode::F31,
            winit::keyboard::KeyCode::F32 => KeyCode::F32,
            winit::keyboard::KeyCode::F33 => KeyCode::F33,
            winit::keyboard::KeyCode::F34 => KeyCode::F34,
            winit::keyboard::KeyCode::F35 => KeyCode::F35,
            _ => KeyCode::Unidentified(yagber_input::keyboard::NativeKeyCode::Unidentified),
        },
    }
}

pub fn convert_logical_key(logical_key_code: &winit::keyboard::Key) -> yagber_input::keyboard::Key {
    use winit::keyboard::{Key, NamedKey};
    match logical_key_code {
        Key::Character(s) => yagber_input::keyboard::Key::Character(s.clone()),
        Key::Unidentified(nk) => yagber_input::keyboard::Key::Unidentified(convert_native_key(nk)),
        Key::Dead(c) => yagber_input::keyboard::Key::Dead(c.to_owned()),
        Key::Named(NamedKey::Alt) => yagber_input::keyboard::Key::Alt,
        Key::Named(NamedKey::AltGraph) => yagber_input::keyboard::Key::AltGraph,
        Key::Named(NamedKey::CapsLock) => yagber_input::keyboard::Key::CapsLock,
        Key::Named(NamedKey::Control) => yagber_input::keyboard::Key::Control,
        Key::Named(NamedKey::Fn) => yagber_input::keyboard::Key::Fn,
        Key::Named(NamedKey::FnLock) => yagber_input::keyboard::Key::FnLock,
        Key::Named(NamedKey::NumLock) => yagber_input::keyboard::Key::NumLock,
        Key::Named(NamedKey::ScrollLock) => yagber_input::keyboard::Key::ScrollLock,
        Key::Named(NamedKey::Shift) => yagber_input::keyboard::Key::Shift,
        Key::Named(NamedKey::Symbol) => yagber_input::keyboard::Key::Symbol,
        Key::Named(NamedKey::SymbolLock) => yagber_input::keyboard::Key::SymbolLock,
        Key::Named(NamedKey::Meta) => yagber_input::keyboard::Key::Meta,
        Key::Named(NamedKey::Hyper) => yagber_input::keyboard::Key::Hyper,
        Key::Named(NamedKey::Super) => yagber_input::keyboard::Key::Super,
        Key::Named(NamedKey::Enter) => yagber_input::keyboard::Key::Enter,
        Key::Named(NamedKey::Tab) => yagber_input::keyboard::Key::Tab,
        Key::Named(NamedKey::Space) => yagber_input::keyboard::Key::Space,
        Key::Named(NamedKey::ArrowDown) => yagber_input::keyboard::Key::ArrowDown,
        Key::Named(NamedKey::ArrowLeft) => yagber_input::keyboard::Key::ArrowLeft,
        Key::Named(NamedKey::ArrowRight) => yagber_input::keyboard::Key::ArrowRight,
        Key::Named(NamedKey::ArrowUp) => yagber_input::keyboard::Key::ArrowUp,
        Key::Named(NamedKey::End) => yagber_input::keyboard::Key::End,
        Key::Named(NamedKey::Home) => yagber_input::keyboard::Key::Home,
        Key::Named(NamedKey::PageDown) => yagber_input::keyboard::Key::PageDown,
        Key::Named(NamedKey::PageUp) => yagber_input::keyboard::Key::PageUp,
        Key::Named(NamedKey::Backspace) => yagber_input::keyboard::Key::Backspace,
        Key::Named(NamedKey::Clear) => yagber_input::keyboard::Key::Clear,
        Key::Named(NamedKey::Copy) => yagber_input::keyboard::Key::Copy,
        Key::Named(NamedKey::CrSel) => yagber_input::keyboard::Key::CrSel,
        Key::Named(NamedKey::Cut) => yagber_input::keyboard::Key::Cut,
        Key::Named(NamedKey::Delete) => yagber_input::keyboard::Key::Delete,
        Key::Named(NamedKey::EraseEof) => yagber_input::keyboard::Key::EraseEof,
        Key::Named(NamedKey::ExSel) => yagber_input::keyboard::Key::ExSel,
        Key::Named(NamedKey::Insert) => yagber_input::keyboard::Key::Insert,
        Key::Named(NamedKey::Paste) => yagber_input::keyboard::Key::Paste,
        Key::Named(NamedKey::Redo) => yagber_input::keyboard::Key::Redo,
        Key::Named(NamedKey::Undo) => yagber_input::keyboard::Key::Undo,
        Key::Named(NamedKey::Accept) => yagber_input::keyboard::Key::Accept,
        Key::Named(NamedKey::Again) => yagber_input::keyboard::Key::Again,
        Key::Named(NamedKey::Attn) => yagber_input::keyboard::Key::Attn,
        Key::Named(NamedKey::Cancel) => yagber_input::keyboard::Key::Cancel,
        Key::Named(NamedKey::ContextMenu) => yagber_input::keyboard::Key::ContextMenu,
        Key::Named(NamedKey::Escape) => yagber_input::keyboard::Key::Escape,
        Key::Named(NamedKey::Execute) => yagber_input::keyboard::Key::Execute,
        Key::Named(NamedKey::Find) => yagber_input::keyboard::Key::Find,
        Key::Named(NamedKey::Help) => yagber_input::keyboard::Key::Help,
        Key::Named(NamedKey::Pause) => yagber_input::keyboard::Key::Pause,
        Key::Named(NamedKey::Play) => yagber_input::keyboard::Key::Play,
        Key::Named(NamedKey::Props) => yagber_input::keyboard::Key::Props,
        Key::Named(NamedKey::Select) => yagber_input::keyboard::Key::Select,
        Key::Named(NamedKey::ZoomIn) => yagber_input::keyboard::Key::ZoomIn,
        Key::Named(NamedKey::ZoomOut) => yagber_input::keyboard::Key::ZoomOut,
        Key::Named(NamedKey::BrightnessDown) => yagber_input::keyboard::Key::BrightnessDown,
        Key::Named(NamedKey::BrightnessUp) => yagber_input::keyboard::Key::BrightnessUp,
        Key::Named(NamedKey::Eject) => yagber_input::keyboard::Key::Eject,
        Key::Named(NamedKey::LogOff) => yagber_input::keyboard::Key::LogOff,
        Key::Named(NamedKey::Power) => yagber_input::keyboard::Key::Power,
        Key::Named(NamedKey::PowerOff) => yagber_input::keyboard::Key::PowerOff,
        Key::Named(NamedKey::PrintScreen) => yagber_input::keyboard::Key::PrintScreen,
        Key::Named(NamedKey::Hibernate) => yagber_input::keyboard::Key::Hibernate,
        Key::Named(NamedKey::Standby) => yagber_input::keyboard::Key::Standby,
        Key::Named(NamedKey::WakeUp) => yagber_input::keyboard::Key::WakeUp,
        Key::Named(NamedKey::AllCandidates) => yagber_input::keyboard::Key::AllCandidates,
        Key::Named(NamedKey::Alphanumeric) => yagber_input::keyboard::Key::Alphanumeric,
        Key::Named(NamedKey::CodeInput) => yagber_input::keyboard::Key::CodeInput,
        Key::Named(NamedKey::Compose) => yagber_input::keyboard::Key::Compose,
        Key::Named(NamedKey::Convert) => yagber_input::keyboard::Key::Convert,
        Key::Named(NamedKey::FinalMode) => yagber_input::keyboard::Key::FinalMode,
        Key::Named(NamedKey::GroupFirst) => yagber_input::keyboard::Key::GroupFirst,
        Key::Named(NamedKey::GroupLast) => yagber_input::keyboard::Key::GroupLast,
        Key::Named(NamedKey::GroupNext) => yagber_input::keyboard::Key::GroupNext,
        Key::Named(NamedKey::GroupPrevious) => yagber_input::keyboard::Key::GroupPrevious,
        Key::Named(NamedKey::ModeChange) => yagber_input::keyboard::Key::ModeChange,
        Key::Named(NamedKey::NextCandidate) => yagber_input::keyboard::Key::NextCandidate,
        Key::Named(NamedKey::NonConvert) => yagber_input::keyboard::Key::NonConvert,
        Key::Named(NamedKey::PreviousCandidate) => yagber_input::keyboard::Key::PreviousCandidate,
        Key::Named(NamedKey::Process) => yagber_input::keyboard::Key::Process,
        Key::Named(NamedKey::SingleCandidate) => yagber_input::keyboard::Key::SingleCandidate,
        Key::Named(NamedKey::HangulMode) => yagber_input::keyboard::Key::HangulMode,
        Key::Named(NamedKey::HanjaMode) => yagber_input::keyboard::Key::HanjaMode,
        Key::Named(NamedKey::JunjaMode) => yagber_input::keyboard::Key::JunjaMode,
        Key::Named(NamedKey::Eisu) => yagber_input::keyboard::Key::Eisu,
        Key::Named(NamedKey::Hankaku) => yagber_input::keyboard::Key::Hankaku,
        Key::Named(NamedKey::Hiragana) => yagber_input::keyboard::Key::Hiragana,
        Key::Named(NamedKey::HiraganaKatakana) => yagber_input::keyboard::Key::HiraganaKatakana,
        Key::Named(NamedKey::KanaMode) => yagber_input::keyboard::Key::KanaMode,
        Key::Named(NamedKey::KanjiMode) => yagber_input::keyboard::Key::KanjiMode,
        Key::Named(NamedKey::Katakana) => yagber_input::keyboard::Key::Katakana,
        Key::Named(NamedKey::Romaji) => yagber_input::keyboard::Key::Romaji,
        Key::Named(NamedKey::Zenkaku) => yagber_input::keyboard::Key::Zenkaku,
        Key::Named(NamedKey::ZenkakuHankaku) => yagber_input::keyboard::Key::ZenkakuHankaku,
        Key::Named(NamedKey::Soft1) => yagber_input::keyboard::Key::Soft1,
        Key::Named(NamedKey::Soft2) => yagber_input::keyboard::Key::Soft2,
        Key::Named(NamedKey::Soft3) => yagber_input::keyboard::Key::Soft3,
        Key::Named(NamedKey::Soft4) => yagber_input::keyboard::Key::Soft4,
        Key::Named(NamedKey::ChannelDown) => yagber_input::keyboard::Key::ChannelDown,
        Key::Named(NamedKey::ChannelUp) => yagber_input::keyboard::Key::ChannelUp,
        Key::Named(NamedKey::Close) => yagber_input::keyboard::Key::Close,
        Key::Named(NamedKey::MailForward) => yagber_input::keyboard::Key::MailForward,
        Key::Named(NamedKey::MailReply) => yagber_input::keyboard::Key::MailReply,
        Key::Named(NamedKey::MailSend) => yagber_input::keyboard::Key::MailSend,
        Key::Named(NamedKey::MediaClose) => yagber_input::keyboard::Key::MediaClose,
        Key::Named(NamedKey::MediaFastForward) => yagber_input::keyboard::Key::MediaFastForward,
        Key::Named(NamedKey::MediaPause) => yagber_input::keyboard::Key::MediaPause,
        Key::Named(NamedKey::MediaPlay) => yagber_input::keyboard::Key::MediaPlay,
        Key::Named(NamedKey::MediaPlayPause) => yagber_input::keyboard::Key::MediaPlayPause,
        Key::Named(NamedKey::MediaRecord) => yagber_input::keyboard::Key::MediaRecord,
        Key::Named(NamedKey::MediaRewind) => yagber_input::keyboard::Key::MediaRewind,
        Key::Named(NamedKey::MediaStop) => yagber_input::keyboard::Key::MediaStop,
        Key::Named(NamedKey::MediaTrackNext) => yagber_input::keyboard::Key::MediaTrackNext,
        Key::Named(NamedKey::MediaTrackPrevious) => yagber_input::keyboard::Key::MediaTrackPrevious,
        Key::Named(NamedKey::New) => yagber_input::keyboard::Key::New,
        Key::Named(NamedKey::Open) => yagber_input::keyboard::Key::Open,
        Key::Named(NamedKey::Print) => yagber_input::keyboard::Key::Print,
        Key::Named(NamedKey::Save) => yagber_input::keyboard::Key::Save,
        Key::Named(NamedKey::SpellCheck) => yagber_input::keyboard::Key::SpellCheck,
        Key::Named(NamedKey::Key11) => yagber_input::keyboard::Key::Key11,
        Key::Named(NamedKey::Key12) => yagber_input::keyboard::Key::Key12,
        Key::Named(NamedKey::AudioBalanceLeft) => yagber_input::keyboard::Key::AudioBalanceLeft,
        Key::Named(NamedKey::AudioBalanceRight) => yagber_input::keyboard::Key::AudioBalanceRight,
        Key::Named(NamedKey::AudioBassBoostDown) => yagber_input::keyboard::Key::AudioBassBoostDown,
        Key::Named(NamedKey::AudioBassBoostToggle) => {
            yagber_input::keyboard::Key::AudioBassBoostToggle
        }
        Key::Named(NamedKey::AudioBassBoostUp) => yagber_input::keyboard::Key::AudioBassBoostUp,
        Key::Named(NamedKey::AudioFaderFront) => yagber_input::keyboard::Key::AudioFaderFront,
        Key::Named(NamedKey::AudioFaderRear) => yagber_input::keyboard::Key::AudioFaderRear,
        Key::Named(NamedKey::AudioSurroundModeNext) => {
            yagber_input::keyboard::Key::AudioSurroundModeNext
        }
        Key::Named(NamedKey::AudioTrebleDown) => yagber_input::keyboard::Key::AudioTrebleDown,
        Key::Named(NamedKey::AudioTrebleUp) => yagber_input::keyboard::Key::AudioTrebleUp,
        Key::Named(NamedKey::AudioVolumeDown) => yagber_input::keyboard::Key::AudioVolumeDown,
        Key::Named(NamedKey::AudioVolumeUp) => yagber_input::keyboard::Key::AudioVolumeUp,
        Key::Named(NamedKey::AudioVolumeMute) => yagber_input::keyboard::Key::AudioVolumeMute,
        Key::Named(NamedKey::MicrophoneToggle) => yagber_input::keyboard::Key::MicrophoneToggle,
        Key::Named(NamedKey::MicrophoneVolumeDown) => {
            yagber_input::keyboard::Key::MicrophoneVolumeDown
        }
        Key::Named(NamedKey::MicrophoneVolumeUp) => yagber_input::keyboard::Key::MicrophoneVolumeUp,
        Key::Named(NamedKey::MicrophoneVolumeMute) => {
            yagber_input::keyboard::Key::MicrophoneVolumeMute
        }
        Key::Named(NamedKey::SpeechCorrectionList) => {
            yagber_input::keyboard::Key::SpeechCorrectionList
        }
        Key::Named(NamedKey::SpeechInputToggle) => yagber_input::keyboard::Key::SpeechInputToggle,
        Key::Named(NamedKey::LaunchApplication1) => yagber_input::keyboard::Key::LaunchApplication1,
        Key::Named(NamedKey::LaunchApplication2) => yagber_input::keyboard::Key::LaunchApplication2,
        Key::Named(NamedKey::LaunchCalendar) => yagber_input::keyboard::Key::LaunchCalendar,
        Key::Named(NamedKey::LaunchContacts) => yagber_input::keyboard::Key::LaunchContacts,
        Key::Named(NamedKey::LaunchMail) => yagber_input::keyboard::Key::LaunchMail,
        Key::Named(NamedKey::LaunchMediaPlayer) => yagber_input::keyboard::Key::LaunchMediaPlayer,
        Key::Named(NamedKey::LaunchMusicPlayer) => yagber_input::keyboard::Key::LaunchMusicPlayer,
        Key::Named(NamedKey::LaunchPhone) => yagber_input::keyboard::Key::LaunchPhone,
        Key::Named(NamedKey::LaunchScreenSaver) => yagber_input::keyboard::Key::LaunchScreenSaver,
        Key::Named(NamedKey::LaunchSpreadsheet) => yagber_input::keyboard::Key::LaunchSpreadsheet,
        Key::Named(NamedKey::LaunchWebBrowser) => yagber_input::keyboard::Key::LaunchWebBrowser,
        Key::Named(NamedKey::LaunchWebCam) => yagber_input::keyboard::Key::LaunchWebCam,
        Key::Named(NamedKey::LaunchWordProcessor) => {
            yagber_input::keyboard::Key::LaunchWordProcessor
        }
        Key::Named(NamedKey::BrowserBack) => yagber_input::keyboard::Key::BrowserBack,
        Key::Named(NamedKey::BrowserFavorites) => yagber_input::keyboard::Key::BrowserFavorites,
        Key::Named(NamedKey::BrowserForward) => yagber_input::keyboard::Key::BrowserForward,
        Key::Named(NamedKey::BrowserHome) => yagber_input::keyboard::Key::BrowserHome,
        Key::Named(NamedKey::BrowserRefresh) => yagber_input::keyboard::Key::BrowserRefresh,
        Key::Named(NamedKey::BrowserSearch) => yagber_input::keyboard::Key::BrowserSearch,
        Key::Named(NamedKey::BrowserStop) => yagber_input::keyboard::Key::BrowserStop,
        Key::Named(NamedKey::AppSwitch) => yagber_input::keyboard::Key::AppSwitch,
        Key::Named(NamedKey::Call) => yagber_input::keyboard::Key::Call,
        Key::Named(NamedKey::Camera) => yagber_input::keyboard::Key::Camera,
        Key::Named(NamedKey::CameraFocus) => yagber_input::keyboard::Key::CameraFocus,
        Key::Named(NamedKey::EndCall) => yagber_input::keyboard::Key::EndCall,
        Key::Named(NamedKey::GoBack) => yagber_input::keyboard::Key::GoBack,
        Key::Named(NamedKey::GoHome) => yagber_input::keyboard::Key::GoHome,
        Key::Named(NamedKey::HeadsetHook) => yagber_input::keyboard::Key::HeadsetHook,
        Key::Named(NamedKey::LastNumberRedial) => yagber_input::keyboard::Key::LastNumberRedial,
        Key::Named(NamedKey::Notification) => yagber_input::keyboard::Key::Notification,
        Key::Named(NamedKey::MannerMode) => yagber_input::keyboard::Key::MannerMode,
        Key::Named(NamedKey::VoiceDial) => yagber_input::keyboard::Key::VoiceDial,
        Key::Named(NamedKey::TV) => yagber_input::keyboard::Key::TV,
        Key::Named(NamedKey::TV3DMode) => yagber_input::keyboard::Key::TV3DMode,
        Key::Named(NamedKey::TVAntennaCable) => yagber_input::keyboard::Key::TVAntennaCable,
        Key::Named(NamedKey::TVAudioDescription) => yagber_input::keyboard::Key::TVAudioDescription,
        Key::Named(NamedKey::TVAudioDescriptionMixDown) => {
            yagber_input::keyboard::Key::TVAudioDescriptionMixDown
        }
        Key::Named(NamedKey::TVAudioDescriptionMixUp) => {
            yagber_input::keyboard::Key::TVAudioDescriptionMixUp
        }
        Key::Named(NamedKey::TVContentsMenu) => yagber_input::keyboard::Key::TVContentsMenu,
        Key::Named(NamedKey::TVDataService) => yagber_input::keyboard::Key::TVDataService,
        Key::Named(NamedKey::TVInput) => yagber_input::keyboard::Key::TVInput,
        Key::Named(NamedKey::TVInputComponent1) => yagber_input::keyboard::Key::TVInputComponent1,
        Key::Named(NamedKey::TVInputComponent2) => yagber_input::keyboard::Key::TVInputComponent2,
        Key::Named(NamedKey::TVInputComposite1) => yagber_input::keyboard::Key::TVInputComposite1,
        Key::Named(NamedKey::TVInputComposite2) => yagber_input::keyboard::Key::TVInputComposite2,
        Key::Named(NamedKey::TVInputHDMI1) => yagber_input::keyboard::Key::TVInputHDMI1,
        Key::Named(NamedKey::TVInputHDMI2) => yagber_input::keyboard::Key::TVInputHDMI2,
        Key::Named(NamedKey::TVInputHDMI3) => yagber_input::keyboard::Key::TVInputHDMI3,
        Key::Named(NamedKey::TVInputHDMI4) => yagber_input::keyboard::Key::TVInputHDMI4,
        Key::Named(NamedKey::TVInputVGA1) => yagber_input::keyboard::Key::TVInputVGA1,
        Key::Named(NamedKey::TVMediaContext) => yagber_input::keyboard::Key::TVMediaContext,
        Key::Named(NamedKey::TVNetwork) => yagber_input::keyboard::Key::TVNetwork,
        Key::Named(NamedKey::TVNumberEntry) => yagber_input::keyboard::Key::TVNumberEntry,
        Key::Named(NamedKey::TVPower) => yagber_input::keyboard::Key::TVPower,
        Key::Named(NamedKey::TVRadioService) => yagber_input::keyboard::Key::TVRadioService,
        Key::Named(NamedKey::TVSatellite) => yagber_input::keyboard::Key::TVSatellite,
        Key::Named(NamedKey::TVSatelliteBS) => yagber_input::keyboard::Key::TVSatelliteBS,
        Key::Named(NamedKey::TVSatelliteCS) => yagber_input::keyboard::Key::TVSatelliteCS,
        Key::Named(NamedKey::TVSatelliteToggle) => yagber_input::keyboard::Key::TVSatelliteToggle,
        Key::Named(NamedKey::TVTerrestrialAnalog) => {
            yagber_input::keyboard::Key::TVTerrestrialAnalog
        }
        Key::Named(NamedKey::TVTerrestrialDigital) => {
            yagber_input::keyboard::Key::TVTerrestrialDigital
        }
        Key::Named(NamedKey::TVTimer) => yagber_input::keyboard::Key::TVTimer,
        Key::Named(NamedKey::AVRInput) => yagber_input::keyboard::Key::AVRInput,
        Key::Named(NamedKey::AVRPower) => yagber_input::keyboard::Key::AVRPower,
        Key::Named(NamedKey::ColorF0Red) => yagber_input::keyboard::Key::ColorF0Red,
        Key::Named(NamedKey::ColorF1Green) => yagber_input::keyboard::Key::ColorF1Green,
        Key::Named(NamedKey::ColorF2Yellow) => yagber_input::keyboard::Key::ColorF2Yellow,
        Key::Named(NamedKey::ColorF3Blue) => yagber_input::keyboard::Key::ColorF3Blue,
        Key::Named(NamedKey::ColorF4Grey) => yagber_input::keyboard::Key::ColorF4Grey,
        Key::Named(NamedKey::ColorF5Brown) => yagber_input::keyboard::Key::ColorF5Brown,
        Key::Named(NamedKey::ClosedCaptionToggle) => {
            yagber_input::keyboard::Key::ClosedCaptionToggle
        }
        Key::Named(NamedKey::Dimmer) => yagber_input::keyboard::Key::Dimmer,
        Key::Named(NamedKey::DisplaySwap) => yagber_input::keyboard::Key::DisplaySwap,
        Key::Named(NamedKey::DVR) => yagber_input::keyboard::Key::DVR,
        Key::Named(NamedKey::Exit) => yagber_input::keyboard::Key::Exit,
        Key::Named(NamedKey::FavoriteClear0) => yagber_input::keyboard::Key::FavoriteClear0,
        Key::Named(NamedKey::FavoriteClear1) => yagber_input::keyboard::Key::FavoriteClear1,
        Key::Named(NamedKey::FavoriteClear2) => yagber_input::keyboard::Key::FavoriteClear2,
        Key::Named(NamedKey::FavoriteClear3) => yagber_input::keyboard::Key::FavoriteClear3,
        Key::Named(NamedKey::FavoriteRecall0) => yagber_input::keyboard::Key::FavoriteRecall0,
        Key::Named(NamedKey::FavoriteRecall1) => yagber_input::keyboard::Key::FavoriteRecall1,
        Key::Named(NamedKey::FavoriteRecall2) => yagber_input::keyboard::Key::FavoriteRecall2,
        Key::Named(NamedKey::FavoriteRecall3) => yagber_input::keyboard::Key::FavoriteRecall3,
        Key::Named(NamedKey::FavoriteStore0) => yagber_input::keyboard::Key::FavoriteStore0,
        Key::Named(NamedKey::FavoriteStore1) => yagber_input::keyboard::Key::FavoriteStore1,
        Key::Named(NamedKey::FavoriteStore2) => yagber_input::keyboard::Key::FavoriteStore2,
        Key::Named(NamedKey::FavoriteStore3) => yagber_input::keyboard::Key::FavoriteStore3,
        Key::Named(NamedKey::Guide) => yagber_input::keyboard::Key::Guide,
        Key::Named(NamedKey::GuideNextDay) => yagber_input::keyboard::Key::GuideNextDay,
        Key::Named(NamedKey::GuidePreviousDay) => yagber_input::keyboard::Key::GuidePreviousDay,
        Key::Named(NamedKey::Info) => yagber_input::keyboard::Key::Info,
        Key::Named(NamedKey::InstantReplay) => yagber_input::keyboard::Key::InstantReplay,
        Key::Named(NamedKey::Link) => yagber_input::keyboard::Key::Link,
        Key::Named(NamedKey::ListProgram) => yagber_input::keyboard::Key::ListProgram,
        Key::Named(NamedKey::LiveContent) => yagber_input::keyboard::Key::LiveContent,
        Key::Named(NamedKey::Lock) => yagber_input::keyboard::Key::Lock,
        Key::Named(NamedKey::MediaApps) => yagber_input::keyboard::Key::MediaApps,
        Key::Named(NamedKey::MediaAudioTrack) => yagber_input::keyboard::Key::MediaAudioTrack,
        Key::Named(NamedKey::MediaLast) => yagber_input::keyboard::Key::MediaLast,
        Key::Named(NamedKey::MediaSkipBackward) => yagber_input::keyboard::Key::MediaSkipBackward,
        Key::Named(NamedKey::MediaSkipForward) => yagber_input::keyboard::Key::MediaSkipForward,
        Key::Named(NamedKey::MediaStepBackward) => yagber_input::keyboard::Key::MediaStepBackward,
        Key::Named(NamedKey::MediaStepForward) => yagber_input::keyboard::Key::MediaStepForward,
        Key::Named(NamedKey::MediaTopMenu) => yagber_input::keyboard::Key::MediaTopMenu,
        Key::Named(NamedKey::NavigateIn) => yagber_input::keyboard::Key::NavigateIn,
        Key::Named(NamedKey::NavigateNext) => yagber_input::keyboard::Key::NavigateNext,
        Key::Named(NamedKey::NavigateOut) => yagber_input::keyboard::Key::NavigateOut,
        Key::Named(NamedKey::NavigatePrevious) => yagber_input::keyboard::Key::NavigatePrevious,
        Key::Named(NamedKey::NextFavoriteChannel) => {
            yagber_input::keyboard::Key::NextFavoriteChannel
        }
        Key::Named(NamedKey::NextUserProfile) => yagber_input::keyboard::Key::NextUserProfile,
        Key::Named(NamedKey::OnDemand) => yagber_input::keyboard::Key::OnDemand,
        Key::Named(NamedKey::Pairing) => yagber_input::keyboard::Key::Pairing,
        Key::Named(NamedKey::PinPDown) => yagber_input::keyboard::Key::PinPDown,
        Key::Named(NamedKey::PinPMove) => yagber_input::keyboard::Key::PinPMove,
        Key::Named(NamedKey::PinPToggle) => yagber_input::keyboard::Key::PinPToggle,
        Key::Named(NamedKey::PinPUp) => yagber_input::keyboard::Key::PinPUp,
        Key::Named(NamedKey::PlaySpeedDown) => yagber_input::keyboard::Key::PlaySpeedDown,
        Key::Named(NamedKey::PlaySpeedReset) => yagber_input::keyboard::Key::PlaySpeedReset,
        Key::Named(NamedKey::PlaySpeedUp) => yagber_input::keyboard::Key::PlaySpeedUp,
        Key::Named(NamedKey::RandomToggle) => yagber_input::keyboard::Key::RandomToggle,
        Key::Named(NamedKey::RcLowBattery) => yagber_input::keyboard::Key::RcLowBattery,
        Key::Named(NamedKey::RecordSpeedNext) => yagber_input::keyboard::Key::RecordSpeedNext,
        Key::Named(NamedKey::RfBypass) => yagber_input::keyboard::Key::RfBypass,
        Key::Named(NamedKey::ScanChannelsToggle) => yagber_input::keyboard::Key::ScanChannelsToggle,
        Key::Named(NamedKey::ScreenModeNext) => yagber_input::keyboard::Key::ScreenModeNext,
        Key::Named(NamedKey::Settings) => yagber_input::keyboard::Key::Settings,
        Key::Named(NamedKey::SplitScreenToggle) => yagber_input::keyboard::Key::SplitScreenToggle,
        Key::Named(NamedKey::STBInput) => yagber_input::keyboard::Key::STBInput,
        Key::Named(NamedKey::STBPower) => yagber_input::keyboard::Key::STBPower,
        Key::Named(NamedKey::Subtitle) => yagber_input::keyboard::Key::Subtitle,
        Key::Named(NamedKey::Teletext) => yagber_input::keyboard::Key::Teletext,
        Key::Named(NamedKey::VideoModeNext) => yagber_input::keyboard::Key::VideoModeNext,
        Key::Named(NamedKey::Wink) => yagber_input::keyboard::Key::Wink,
        Key::Named(NamedKey::ZoomToggle) => yagber_input::keyboard::Key::ZoomToggle,
        Key::Named(NamedKey::F1) => yagber_input::keyboard::Key::F1,
        Key::Named(NamedKey::F2) => yagber_input::keyboard::Key::F2,
        Key::Named(NamedKey::F3) => yagber_input::keyboard::Key::F3,
        Key::Named(NamedKey::F4) => yagber_input::keyboard::Key::F4,
        Key::Named(NamedKey::F5) => yagber_input::keyboard::Key::F5,
        Key::Named(NamedKey::F6) => yagber_input::keyboard::Key::F6,
        Key::Named(NamedKey::F7) => yagber_input::keyboard::Key::F7,
        Key::Named(NamedKey::F8) => yagber_input::keyboard::Key::F8,
        Key::Named(NamedKey::F9) => yagber_input::keyboard::Key::F9,
        Key::Named(NamedKey::F10) => yagber_input::keyboard::Key::F10,
        Key::Named(NamedKey::F11) => yagber_input::keyboard::Key::F11,
        Key::Named(NamedKey::F12) => yagber_input::keyboard::Key::F12,
        Key::Named(NamedKey::F13) => yagber_input::keyboard::Key::F13,
        Key::Named(NamedKey::F14) => yagber_input::keyboard::Key::F14,
        Key::Named(NamedKey::F15) => yagber_input::keyboard::Key::F15,
        Key::Named(NamedKey::F16) => yagber_input::keyboard::Key::F16,
        Key::Named(NamedKey::F17) => yagber_input::keyboard::Key::F17,
        Key::Named(NamedKey::F18) => yagber_input::keyboard::Key::F18,
        Key::Named(NamedKey::F19) => yagber_input::keyboard::Key::F19,
        Key::Named(NamedKey::F20) => yagber_input::keyboard::Key::F20,
        Key::Named(NamedKey::F21) => yagber_input::keyboard::Key::F21,
        Key::Named(NamedKey::F22) => yagber_input::keyboard::Key::F22,
        Key::Named(NamedKey::F23) => yagber_input::keyboard::Key::F23,
        Key::Named(NamedKey::F24) => yagber_input::keyboard::Key::F24,
        Key::Named(NamedKey::F25) => yagber_input::keyboard::Key::F25,
        Key::Named(NamedKey::F26) => yagber_input::keyboard::Key::F26,
        Key::Named(NamedKey::F27) => yagber_input::keyboard::Key::F27,
        Key::Named(NamedKey::F28) => yagber_input::keyboard::Key::F28,
        Key::Named(NamedKey::F29) => yagber_input::keyboard::Key::F29,
        Key::Named(NamedKey::F30) => yagber_input::keyboard::Key::F30,
        Key::Named(NamedKey::F31) => yagber_input::keyboard::Key::F31,
        Key::Named(NamedKey::F32) => yagber_input::keyboard::Key::F32,
        Key::Named(NamedKey::F33) => yagber_input::keyboard::Key::F33,
        Key::Named(NamedKey::F34) => yagber_input::keyboard::Key::F34,
        Key::Named(NamedKey::F35) => yagber_input::keyboard::Key::F35,
        _ => todo!(),
    }
}

pub fn convert_native_key(
    native_key: &winit::keyboard::NativeKey,
) -> yagber_input::keyboard::NativeKey {
    use winit::keyboard::NativeKey;
    match native_key {
        NativeKey::Unidentified => yagber_input::keyboard::NativeKey::Unidentified,
        NativeKey::Android(v) => yagber_input::keyboard::NativeKey::Android(*v),
        NativeKey::MacOS(v) => yagber_input::keyboard::NativeKey::MacOS(*v),
        NativeKey::Windows(v) => yagber_input::keyboard::NativeKey::Windows(*v),
        NativeKey::Xkb(v) => yagber_input::keyboard::NativeKey::Xkb(*v),
        NativeKey::Web(v) => yagber_input::keyboard::NativeKey::Web(v.clone()),
    }
}
