[package]
name = "yagber_memory"
version = "0.1.0"
edition = "2024"

[dependencies]
arbitrary-int = { workspace = true }

[features]
default = ["break_on_unitialized_ram_read"]
break_on_unitialized_ram_read = []
