name: Rust tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-script
        run: |
          cargo install rust-script --locked

      - name: Fetch test ROMs
        run: |
          rust-script scripts/fetch_test_roms.rs

      - name: Build tests
        run: |
          cargo test --release --workspace --no-run

      - name: Run tests
        run: |
          cargo test --release --workspace --no-fail-fast