name: Rust tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain (stable)
        uses: dtolnay/rust-toolchain@v1

      - name: Install cargo-script
        run: |
          cargo install rust-script --locked

      - name: Fetch test ROMs
        run: |
          rust-script scripts/fetch_test_roms.rs

      - name: Run tests
        run: |
          cargo test --release --workspace